import { redirect } from 'next/navigation'
import { head } from '@vercel/blob'

interface Props {
  params: Promise<{ jobId: string }>
}

export default async function MapPage({ params }: Props) {
  const { jobId } = await params

  // Validate job ID format (16 hex chars)
  if (!/^[a-f0-9]{16}$/i.test(jobId)) {
    redirect('/maps/expired')
  }

  try {
    // Check if blob exists by looking for the index.html
    const blobInfo = await head(`maps/${jobId}/index.html`)

    if (blobInfo && blobInfo.url) {
      // Redirect to the actual blob URL
      redirect(blobInfo.url)
    }
  } catch {
    // Blob not found or error - redirect to expired page
  }

  redirect('/maps/expired')
}

// Generate metadata for the page
export async function generateMetadata({ params }: Props) {
  const { jobId } = await params
  return {
    title: `PEIT Map - ${jobId}`,
    description: 'Interactive environmental map generated by PEIT Map Creator',
  }
}
