import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Header } from '@/components/header'

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-3xl mx-auto">
          <Button variant="ghost" size="sm" asChild className="mb-6">
            <Link href="/">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Home
            </Link>
          </Button>

          <article className="prose dark:prose-invert max-w-none">
            <h1>Terms of Service</h1>
            <p className="text-muted-foreground">Last updated: December 22, 2025</p>

            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using PEIT Map Creator ("the Service"), you agree to be bound by these
              Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              PEIT Map Creator is a free tool that generates interactive environmental maps by
              querying publicly available ArcGIS FeatureServer REST APIs. The Service processes
              user-uploaded geospatial files to identify environmental features that intersect
              with provided geometries.
            </p>

            <h2>3. User Responsibilities</h2>
            <p>When using the Service, you agree to:</p>
            <ul>
              <li>Provide accurate information during account registration</li>
              <li>Only upload files you have the right to use</li>
              <li>Not upload content that is illegal, harmful, or violates third-party rights</li>
              <li>Not attempt to circumvent rate limits or abuse the Service</li>
              <li>Not use the Service for any unlawful purpose</li>
            </ul>

            <h2>4. Data and Privacy</h2>
            <p>
              Your use of the Service is also governed by our{' '}
              <Link href="/privacy" className="text-primary hover:underline">
                Privacy Policy
              </Link>
              , which describes how we collect, use, and protect your data.
            </p>

            <h2>5. Generated Maps</h2>
            <p>
              Maps generated by the Service are stored for <strong>7 days</strong> and are accessible
              via unique URLs. These URLs are <strong>unlisted</strong> (not indexed by search engines)
              but are <strong>not private</strong>—anyone with the link can view the map. Do not share
              map URLs if the underlying data is sensitive or confidential.
            </p>

            <h2>6. Intellectual Property</h2>
            <p>
              You retain all rights to the geospatial files you upload. By using the Service, you
              grant us a limited license to process your files solely for the purpose of generating
              your requested maps. We do not claim ownership of your data.
            </p>
            <p>
              Environmental data displayed in generated maps is sourced from publicly available
              government databases and remains subject to their respective terms of use.
            </p>

            <h2>7. Service Availability</h2>
            <p>
              The Service is provided on an "as is" and "as available" basis. We do not guarantee:
            </p>
            <ul>
              <li>Uninterrupted or error-free operation</li>
              <li>The accuracy, completeness, or timeliness of environmental data</li>
              <li>That the Service will meet your specific requirements</li>
            </ul>
            <p>
              We reserve the right to modify, suspend, or discontinue the Service at any time
              without prior notice.
            </p>

            <h2>8. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, PEIT Map Creator and its operators shall not
              be liable for any indirect, incidental, special, consequential, or punitive damages
              arising from your use of the Service. This includes but is not limited to:
            </p>
            <ul>
              <li>Loss of data or business opportunities</li>
              <li>Reliance on environmental data for permitting decisions</li>
              <li>Errors or omissions in generated maps or reports</li>
            </ul>
            <p>
              <strong>Important:</strong> Generated maps are for informational purposes only and
              should not be used as the sole basis for environmental permitting decisions. Always
              verify data with authoritative sources.
            </p>

            <h2>9. Account Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account if you violate these Terms
              of Service or engage in behavior that harms the Service or other users.
            </p>

            <h2>10. Changes to Terms</h2>
            <p>
              We may update these Terms of Service from time to time. Continued use of the Service
              after changes constitutes acceptance of the new terms. We encourage you to review
              this page periodically.
            </p>

            <h2>11. Contact</h2>
            <p>
              If you have questions about these Terms of Service, please visit our{' '}
              <a
                href="https://github.com/lukaskucinski/peit_map_creator"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary hover:underline"
              >
                GitHub repository
              </a>{' '}
              to open an issue or discussion.
            </p>
          </article>
        </div>
      </main>
    </div>
  )
}

export const metadata = {
  title: 'Terms of Service - PEIT Map Creator',
  description: 'Terms of Service for PEIT Map Creator, a free environmental mapping tool.',
}
