import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />
      <main className="container mx-auto px-4 py-8 flex-1">
        <div className="max-w-3xl mx-auto">
          <Button variant="ghost" size="sm" asChild className="mb-6">
            <Link href="/">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Home
            </Link>
          </Button>

          {/* Page Header */}
          <div className="mb-8">
            <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
            <p className="text-muted-foreground">Last updated: December 22, 2025</p>
          </div>

          {/* Quick Summary */}
          <div className="bg-muted/50 border rounded-lg p-4 mb-8">
            <p className="text-sm text-muted-foreground">
              <strong className="text-foreground">Summary:</strong> PEIT Map Creator is a free tool for generating environmental maps.
              By using it, you agree to use it responsibly, understand that generated maps are stored for 7 days
              and are not private, and acknowledge that the data is for informational purposes only.
            </p>
          </div>

          {/* Sections */}
          <div className="space-y-8">

            {/* Section 1 */}
            <section>
              <h2 className="text-xl font-semibold mb-3 pb-2 border-b">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                By accessing or using PEIT Map Creator (&ldquo;the Service&rdquo;), you agree to be bound by these
                Terms of Service. If you do not agree to these terms, please do not use the Service.
              </p>
            </section>

            {/* Section 2 */}
            <section>
              <h2 className="text-xl font-semibold mb-3 pb-2 border-b">2. Description of Service</h2>
              <p className="text-muted-foreground leading-relaxed">
                PEIT Map Creator is a tool that generates interactive environmental maps by
                querying publicly available ArcGIS FeatureServer REST APIs. The Service processes
                user-uploaded geospatial files to identify environmental features that intersect
                with provided geometries.
              </p>
            </section>

            {/* Section 3 */}
            <section>
              <h2 className="text-xl font-semibold mb-3 pb-2 border-b">3. User Responsibilities</h2>
              <p className="text-muted-foreground leading-relaxed mb-3">When using the Service, you agree to:</p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-2">
                <li>Provide accurate information during account registration</li>
                <li>Only upload files you have the right to use</li>
                <li>Not upload content that is illegal, harmful, or violates third-party rights</li>
                <li>Not attempt to circumvent rate limits or abuse the Service</li>
                <li>Not use the Service for any unlawful purpose</li>
              </ul>
            </section>

            {/* Section 4 */}
            <section>
              <h2 className="text-xl font-semibold mb-3 pb-2 border-b">4. Data and Privacy</h2>
              <p className="text-muted-foreground leading-relaxed">
                Your use of the Service is also governed by our{' '}
                <Link href="/privacy" className="text-primary hover:underline font-medium">
                  Privacy Policy
                </Link>
                , which describes how we collect, use, and protect your data.
              </p>
            </section>

            {/* Section 5 - Important callout */}
            <section>
              <h2 className="text-xl font-semibold mb-3 pb-2 border-b">5. Generated Maps</h2>
              <div className="bg-amber-500/10 border border-amber-500/20 rounded-lg p-4 mb-3">
                <p className="text-sm">
                  <strong className="text-amber-600 dark:text-amber-400">Important:</strong> Maps are{' '}
                  <strong>unlisted</strong> (not indexed by search engines) but{' '}
                  <strong>not private</strong>—anyone with the link can view the map.
                </p>
              </div>
              <p className="text-muted-foreground leading-relaxed">
                Maps generated by the Service are stored for <strong className="text-foreground">7 days</strong> and
                are accessible via unique URLs. Do not share map URLs if the underlying data is sensitive or confidential.
              </p>
            </section>

            {/* Section 6 */}
            <section>
              <h2 className="text-xl font-semibold mb-3 pb-2 border-b">6. Intellectual Property</h2>
              <div className="space-y-3 text-muted-foreground leading-relaxed">
                <p>
                  <strong className="text-foreground">Your data:</strong> You retain all rights to the geospatial files you upload.
                  By using the Service, you grant us a limited license to process your files solely for the purpose of generating
                  your requested maps. We do not claim ownership of your data.
                </p>
                <p>
                  <strong className="text-foreground">Environmental data:</strong> Data displayed in generated maps is sourced from
                  publicly available government databases and remains subject to their respective terms of use.
                </p>
              </div>
            </section>

            {/* Section 7 */}
            <section>
              <h2 className="text-xl font-semibold mb-3 pb-2 border-b">7. Service Availability</h2>
              <p className="text-muted-foreground leading-relaxed mb-3">
                The Service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. We do not guarantee:
              </p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-2 mb-3">
                <li>Uninterrupted or error-free operation</li>
                <li>The accuracy, completeness, or timeliness of environmental data</li>
                <li>That the Service will meet your specific requirements</li>
              </ul>
              <p className="text-muted-foreground leading-relaxed">
                We reserve the right to modify, suspend, or discontinue the Service at any time without prior notice.
              </p>
            </section>

            {/* Section 8 - Important callout */}
            <section>
              <h2 className="text-xl font-semibold mb-3 pb-2 border-b">8. Limitation of Liability</h2>
              <p className="text-muted-foreground leading-relaxed mb-3">
                To the fullest extent permitted by law, PEIT Map Creator and its operators shall not
                be liable for any indirect, incidental, special, consequential, or punitive damages
                arising from your use of the Service, including but not limited to:
              </p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-2 mb-4">
                <li>Loss of data or business opportunities</li>
                <li>Reliance on environmental data for permitting decisions</li>
                <li>Errors or omissions in generated maps or reports</li>
              </ul>
              <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
                <p className="text-sm">
                  <strong className="text-blue-600 dark:text-blue-400">Note:</strong> Generated maps are for{' '}
                  <strong>informational purposes only</strong> and should not be used as the sole basis for
                  environmental permitting decisions. Always verify data with authoritative sources.
                </p>
              </div>
            </section>

            {/* Section 9 */}
            <section>
              <h2 className="text-xl font-semibold mb-3 pb-2 border-b">9. Account Termination</h2>
              <p className="text-muted-foreground leading-relaxed">
                We reserve the right to suspend or terminate your account if you violate these Terms
                of Service or engage in behavior that harms the Service or other users.
              </p>
            </section>

            {/* Section 10 */}
            <section>
              <h2 className="text-xl font-semibold mb-3 pb-2 border-b">10. Changes to Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                We may update these Terms of Service from time to time. Continued use of the Service
                after changes constitutes acceptance of the new terms. We encourage you to review
                this page periodically.
              </p>
            </section>

            {/* Section 11 */}
            <section>
              <h2 className="text-xl font-semibold mb-3 pb-2 border-b">11. Contact</h2>
              <p className="text-muted-foreground leading-relaxed">
                If you have questions about these Terms of Service, please visit our{' '}
                <a
                  href="https://github.com/lukaskucinski/peit_map_creator"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary hover:underline font-medium"
                >
                  GitHub repository
                </a>{' '}
                to open an issue or discussion.
              </p>
            </section>

          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}

export const metadata = {
  title: 'Terms of Service - PEIT Map Creator',
  description: 'Terms of Service for PEIT Map Creator, a free environmental mapping tool.',
}
